server:
  port: ${SERVER_PORT:8089}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/time_deposit}
    username: ${DB_USERNAME:time_deposit}
    password: ${DB_PASSWORD:time_deposit}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
management:
  endpoints:
    web:
      exposure:
        include: health,info
